[package]
name = "twitch-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
chat-gpt-lib-rs = "0.5.1"
dotenvy = "0.15.7"
rand = "0.8.5"
tokio = "1.39.2"
twitch-irc = "5.0.1"

[target.x86_64-pc-windows-msvc]
linker = "x86_64-w64-mingw32-gcc"
